[2024-11-04T00:00:02.373+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_pipeline.extract_users scheduled__2024-11-03T00:00:00+00:00 [queued]>
[2024-11-04T00:00:02.379+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_pipeline.extract_users scheduled__2024-11-03T00:00:00+00:00 [queued]>
[2024-11-04T00:00:02.379+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-11-04T00:00:02.390+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_users> on 2024-11-03 00:00:00+00:00
[2024-11-04T00:00:02.393+0000] {standard_task_runner.py:57} INFO - Started process 468 to run task
[2024-11-04T00:00:02.395+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_pipeline', 'extract_users', 'scheduled__2024-11-03T00:00:00+00:00', '--job-id', '814', '--raw', '--subdir', 'DAGS_FOLDER/user_pipeline.py', '--cfg-path', '/tmp/tmp_rixomx_']
[2024-11-04T00:00:02.396+0000] {standard_task_runner.py:85} INFO - Job 814: Subtask extract_users
[2024-11-04T00:00:02.434+0000] {task_command.py:415} INFO - Running <TaskInstance: user_pipeline.extract_users scheduled__2024-11-03T00:00:00+00:00 [running]> on host aa6419ae5165
[2024-11-04T00:00:02.495+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_pipeline' AIRFLOW_CTX_TASK_ID='extract_users' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-03T00:00:00+00:00'
[2024-11-04T00:00:02.497+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/user_pipeline.py", line 13, in extract_users
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.3), port 5432 failed: fe_sendauth: no password supplied

[2024-11-04T00:00:02.502+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=user_pipeline, task_id=extract_users, execution_date=20241103T000000, start_date=20241104T000002, end_date=20241104T000002
[2024-11-04T00:00:02.512+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 814 for task extract_users (connection to server at "postgres" (172.18.0.3), port 5432 failed: fe_sendauth: no password supplied
; 468)
[2024-11-04T00:00:02.536+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-04T00:00:02.554+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-04T18:37:49.439+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_pipeline.extract_users scheduled__2024-11-03T00:00:00+00:00 [queued]>
[2024-11-04T18:37:49.445+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_pipeline.extract_users scheduled__2024-11-03T00:00:00+00:00 [queued]>
[2024-11-04T18:37:49.446+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-11-04T18:37:49.456+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_users> on 2024-11-03 00:00:00+00:00
[2024-11-04T18:37:49.460+0000] {standard_task_runner.py:57} INFO - Started process 135 to run task
[2024-11-04T18:37:49.462+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_pipeline', 'extract_users', 'scheduled__2024-11-03T00:00:00+00:00', '--job-id', '846', '--raw', '--subdir', 'DAGS_FOLDER/user_pipeline.py', '--cfg-path', '/tmp/tmpg09ggiti']
[2024-11-04T18:37:49.463+0000] {standard_task_runner.py:85} INFO - Job 846: Subtask extract_users
[2024-11-04T18:37:49.497+0000] {task_command.py:415} INFO - Running <TaskInstance: user_pipeline.extract_users scheduled__2024-11-03T00:00:00+00:00 [running]> on host 2b06df56fdc4
[2024-11-04T18:37:49.551+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_pipeline' AIRFLOW_CTX_TASK_ID='extract_users' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-03T00:00:00+00:00'
[2024-11-04T18:37:49.565+0000] {logging_mixin.py:151} INFO - Usuarios extraídos: [(1, 'John', 'Doe', 'john.doe@example.com', 30), (2, 'Jane', 'Smith', 'jane.smith@example.com', 25), (3, 'Alice', 'Johnson', 'alice.johnson@example.com', 28)]
[2024-11-04T18:37:49.565+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-11-04T18:37:49.573+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=user_pipeline, task_id=extract_users, execution_date=20241103T000000, start_date=20241104T183749, end_date=20241104T183749
[2024-11-04T18:37:49.594+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-11-04T18:37:49.613+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-04T18:48:48.796+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_pipeline.extract_users scheduled__2024-11-03T00:00:00+00:00 [queued]>
[2024-11-04T18:48:48.803+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_pipeline.extract_users scheduled__2024-11-03T00:00:00+00:00 [queued]>
[2024-11-04T18:48:48.803+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-11-04T18:48:48.813+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_users> on 2024-11-03 00:00:00+00:00
[2024-11-04T18:48:48.816+0000] {standard_task_runner.py:57} INFO - Started process 155 to run task
[2024-11-04T18:48:48.819+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_pipeline', 'extract_users', 'scheduled__2024-11-03T00:00:00+00:00', '--job-id', '858', '--raw', '--subdir', 'DAGS_FOLDER/user_pipeline.py', '--cfg-path', '/tmp/tmpphdd9798']
[2024-11-04T18:48:48.819+0000] {standard_task_runner.py:85} INFO - Job 858: Subtask extract_users
[2024-11-04T18:48:48.853+0000] {task_command.py:415} INFO - Running <TaskInstance: user_pipeline.extract_users scheduled__2024-11-03T00:00:00+00:00 [running]> on host 9b393f9117ee
[2024-11-04T18:48:48.908+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_pipeline' AIRFLOW_CTX_TASK_ID='extract_users' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-03T00:00:00+00:00'
[2024-11-04T18:48:48.922+0000] {logging_mixin.py:151} INFO - Usuarios extraídos: [(1, 'John', 'Doe', 'john.doe@example.com', 30), (2, 'Jane', 'Smith', 'jane.smith@example.com', 25), (3, 'Alice', 'Johnson', 'alice.johnson@example.com', 28)]
[2024-11-04T18:48:48.922+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-11-04T18:48:48.929+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=user_pipeline, task_id=extract_users, execution_date=20241103T000000, start_date=20241104T184848, end_date=20241104T184848
[2024-11-04T18:48:48.951+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-11-04T18:48:48.970+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
